hackersatcambridge/hac-website

- gulpfile.js
> Fix crash on Stylus error

- README.md
Merge this before doing pull request #16
> Add Unit Testing info to README.md

- Views/home.stencil
- Views/layouts/base.stencil
- Views/layouts/default.stencil
- Views/workshops.stencil
- static/src/styles/colours.styl
- static/src/styles/fonts.styl
- static/src/styles/main.styl
Just laying down a starting point for us to iterate on, just opening PR for completeness sake. Let's make this beautiful!
> Add some home page markup and styles

- gulpfile.js
- Move from using yucky strings to yummy functions
- Keep the reload server task running until the server is actually reloaded 🙄 (Fixes #43 )
> Give gulpfile some love

- Sources/HaCWebsiteLib/ViewModels/LandingPage.swift
- static/src/styles/landing/LandingTop.styl
> Fix capitalisation issues

- Sources/HaCWebsiteLib/Controllers/EventStreamController.swift
- Sources/HaCWebsiteLib/ViewModels/EventStream.swift
- Sources/HaCWebsiteLib/ViewModels/LandingUpdateFeed.swift
- Sources/HaCWebsiteLib/routes.swift
> Create a route `beta/event-stream` for developing the event stream

- README.md
Fix the header and clarify the instructions for the .env file.
> Make minor fixes to README

- Sources/HaCWebsiteLib/ViewModels/LandingPage.swift
Links people to the details page rather than the Facebook page
> Update intro link

- Sources/HaCWebsiteLib/ViewModels/LandingFeatures/IntroToProgramming2.swift
> Point intro link to the repo

- Sources/HaCWebsiteLib/ViewModels/LandingPage/LandingFeatures/GitWorkshop.swift
- Sources/HaCWebsiteLib/routes.swift
> Add Git link

- Sources/HaCWebsiteLib/routes.swift
Updated as a new repository is needed for the new complex material.
> Change the intro to programming redirector

- Sources/HaCTML/Fragment.swift
> Fix Fragment supporting only Node and not Nodeable

- static/src/styles/core/fonts.styl
- static/src/styles/core/text.styl
Roboto yucky. Barlow yummy.
Previously
Now
> Change body font to Barlow

- Sources/HaCWebsiteLib/routes.swift
> Make `/gamegig` link to Facebook event

- Sources/HaCWebsiteLib/ViewModels/LandingPage/LandingFeatures/BinaryExploitation.swift
Forgot Asset so image wasn't loading on prod
> Fix asset references

- Sources/HaCWebsiteLib/ViewModels/LandingPage/LandingFeatures/IntroToUnity.swift
- Sources/HaCWebsiteLib/routes.swift
> Add actual livelink for unity

- Sources/HaCWebsiteLib/ViewModels/LandingPage/LandingFeatures/IntroToUnity.swift
- Sources/HaCWebsiteLib/ViewModels/LandingPage/LandingFeatures/LandingFeatures.swift
- Sources/HaCWebsiteLib/routes.swift
> Force unity Feature

- Sources/HaCWebsiteLib/ViewModels/Hackathons/GameGig2017/GameGig2017.swift
> Update lunch time to 13:00

- Sources/HaCWebsiteLib/ViewModels/LandingPage/LandingFeatures/LandingFeatures.swift
> Disable unity feature

- Sources/HaCWebsiteLib/ViewModels/Hackathons/GameGig2017/GameGig2017.swift
> Add new links to GameGig

- Sources/HaCWebsiteLib/ViewModels/Hackathons/GameGig2017/GameGig2017.swift
Add game gig voting (do not merge until later)
> Game gig voting

- README.md
- Sources/HaCWebsiteLib/routes.swift
> Add references to API documentation

- Sources/HaCWebsiteLib/Utils/GitUtil.swift
Oopsie daisy.
Verified that it works this time!
> Fix getting of Git commit SHA

- Sources/HaCWebsiteLib/Models/NewWorkshop+init.swift
- Sources/HaCWebsiteLib/Models/NewWorkshop.swift
- Sources/HaCWebsiteLib/NewWorkshopManager.swift
Makes the presenter guide optional for workshop repositories
> Make presenter guide optional

- Package.resolved
- Sources/HaCWebsite/main.swift
- Sources/HaCWebsiteLib/Controllers/WorkshopsController.swift
- Sources/HaCWebsiteLib/NewWorkshopManager.swift
- Sources/HaCWebsiteLib/routes.swift
Fixes #199
- Polls for updates to workshops
- Provides a password-protected update trigger endpoint
> Keep workshops up-to-date

- Sources/HaCWebsiteLib/Models/Workshop.swift
- Sources/HaCWebsiteLib/Views/LandingPage/LandingFeatures/ContinuousIntegrationWorkshop.swift
- Sources/HaCWebsiteLib/Views/LandingPage/LandingFeatures/LandingFeatures.swift
- Sources/HaCWebsiteLib/Views/Workshops/IndividualWorkshopPage.swift
> Add a Continous Integration Workshop feature

- Sources/HaCWebsiteLib/WorkshopManager.swift
> Rename workshops-refactor repository to workhops

- Sources/HaCWebsiteLib/WorkshopManager.swift
> Increase polling interval to 5 minutes

- Sources/HaCWebsiteLib/Views/LandingPage/LandingFeatures/EmacsWorkshop.swift
- Sources/HaCWebsiteLib/Views/LandingPage/LandingFeatures/LandingFeatures.swift
> Add emacs feature

- Sources/HaCWebsiteLib/Views/LandingPage/LandingFeatures/IntroToSwift.swift
- Sources/HaCWebsiteLib/Views/LandingPage/LandingFeatures/LandingFeatures.swift
> Add Swift workshop feature

- Sources/HaCWebsiteLib/Config.swift
- docker-compose.yml
> Add new environment variable checks to Config.swift

- Sources/HaCWebsiteLib/Views/LandingPage/LandingFeatures/LandingFeatures.swift
- Sources/HaCWebsiteLib/Views/LandingPage/LandingFeatures/OpenSourceWorkshop.swift
> Add open source feature

- Sources/HaCWebsiteLib/Views/LandingPage/LandingFeatures/LandingFeatures.swift
- Sources/HaCWebsiteLib/Views/LandingPage/LandingFeatures/WebDevWorkshop.swift
> Add web dev features

- Sources/HaCWebsiteLib/Utils/DateUtils.swift
- Sources/HaCWebsiteLib/Views/LandingPage/EventFeature.swift
Added time on featured today event
Along with this I added an individualTimeFormatter in DateUtils
> Add event start time to featured event

- Sources/HaCWebsiteLib/Views/LandingPage/EventFeature.swift
- Sources/HaCWebsiteLib/Views/LandingPage/LandingFeatures/BashWorkshop.swift
- Sources/HaCWebsiteLib/Views/LandingPage/LandingFeatures/BinaryExploitation.swift
- Sources/HaCWebsiteLib/Views/LandingPage/LandingFeatures/ContinuousIntegrationWorkshop.swift
- Sources/HaCWebsiteLib/Views/LandingPage/LandingFeatures/EmacsWorkshop.swift
- Sources/HaCWebsiteLib/Views/LandingPage/LandingFeatures/GameGig.swift
- Sources/HaCWebsiteLib/Views/LandingPage/LandingFeatures/GamesWithLove.swift
- Sources/HaCWebsiteLib/Views/LandingPage/LandingFeatures/GitWorkshop.swift
- Sources/HaCWebsiteLib/Views/LandingPage/LandingFeatures/IntroToProgramming1.swift
- Sources/HaCWebsiteLib/Views/LandingPage/LandingFeatures/IntroToProgramming2.swift
- Sources/HaCWebsiteLib/Views/LandingPage/LandingFeatures/IntroToProgramming3.swift
- Sources/HaCWebsiteLib/Views/LandingPage/LandingFeatures/IntroToProgramming4.swift
- Sources/HaCWebsiteLib/Views/LandingPage/LandingFeatures/IntroToSwift.swift
- Sources/HaCWebsiteLib/Views/LandingPage/LandingFeatures/IntroToUnity.swift
- Sources/HaCWebsiteLib/Views/LandingPage/LandingFeatures/OpenSourceWorkshop.swift
- Sources/HaCWebsiteLib/Views/LandingPage/LandingFeatures/ProgrammingInRust.swift
- Sources/HaCWebsiteLib/Views/LandingPage/LandingFeatures/PythonML.swift
- Sources/HaCWebsiteLib/Views/LandingPage/LandingFeatures/WebDevWorkshop.swift
- static/src/styles/EventFeature.styl
+ EventFeature.styl: Added a background and rounded border for the overlay text
- EventFeature.swift: Modified `TextShade` enum to resolve as `EventFeature--text-light`.
Fixes #239.
> Event Feature text overlay - background added for contrast

- Sources/HaCWebsiteLib/routes.swift
Not a perfect solution, but works for now. Definitely a discussion point in the future about how we're going to manage the site and adding newer content.
> Add redirect to game gig one button edition

- Sources/HaCWebsiteLib/routes.swift
Reverts hackersatcambridge/hac-website#274
> Revert "Add redirect to game gig one button edition"

- Sources/HaCWebsiteLib/routes.swift
Adding game gig one button edition redirects to the router
> Add Game Gig 2018 redirects
