Dockerfile

Fixes issue #5, desired as it's more secure than npm. (See Issue)

Install Yarn without NPM

---

Dockerfile
package.json

This PR fixes an issue which was preventing people from cloning the repo and starting up the server properly unless they had a docker image with a specific node version installed.

Fix node engine version to use 6.11.3

---

Dockerfile

```bash
[WARNING]: Empty continuation line found in:
RUN   export DEBIAN_FRONTEND=noninteractive &&   apt-get update &&   apt-get install curl apt-transport-https &&   curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash - &&   curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - &&   echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list &&   apt-get update &&   apt-get install nodejs yarn &&   npm install -g n &&   n 6.11.3
[WARNING]: Empty continuation lines will become errors in a future release.
```

Fix warning during `docker-compose build`

---

.swiftlint.yml
Sources/HaCTML/Attribute.swift
Sources/HaCTML/AttributeMap.swift
Sources/HaCTML/Attributes.swift
Sources/HaCTML/Elements.swift
Sources/HaCTML/Fragment.swift
Sources/HaCTML/HTMLElement.swift
Sources/HaCTML/TextNode.swift
Sources/HaCTML/render.swift
Sources/HaCWebsite/main.swift
Sources/HaCWebsiteLib/Config.swift
Sources/HaCWebsiteLib/Controllers/LandingPageController.swift
Sources/HaCWebsiteLib/GitUtils.swift
Sources/HaCWebsiteLib/ViewModels/LandingPage.swift
Sources/HaCWebsiteLib/ViewModels/PostCard.swift
Sources/HaCWebsiteLib/Workshop.swift
Sources/HaCWebsiteLib/WorkshopManager.swift
Sources/HaCWebsiteLib/routes.swift

This PR adds support for [SwiftLint](https://github.com/realm/SwiftLint), configures some rules that were particularly grating, and fixes all of the offenders in our current codebase.
Caveats:
- Fixing is only partially automatic. There is a `swiftlint autocorrect` feature but will leave many rules for manual fixing
- Have not got it configured with Docker. Linux support exists but takes some love. So for this time, it's Mac only and not integrated into our CI builds.
I also did a teeny weeny bit of refactoring (only a little bit).

Add SwiftLint support

---

Sources/HaCWebsiteLib/Controllers/RedirectsMiddleware.swift
Sources/HaCWebsiteLib/routes.swift

This gives us the ability to make a list of static redirects from paths to arbitrary URL strings.
Included is a redirect to our "Intro to programming" workshop.

Add generic redirects middleware + intro redirect

---

Sources/HaCWebsiteLib/routes.swift

In rearranging some routes in a previous PR, I broke the whole site. Let's undo that.

Move not found handler to later position

---

Sources/HaCWebsiteLib/ViewModels/LandingPage/EventFeature.swift
static/src/styles/EventFeature.styl

Tells ya when the event's happening right now
Previously
Now

Label events 'live now' when appropriate

---

Sources/HaCWebsiteLib/Utils/GitUtils.swift

GitUtils wasn't respecting the `repoURL` argument

Fix bug in GitUtils

---

Sources/HaCWebsite/main.swift
Sources/HaCWebsiteLib/ConstitutionManager.swift
Sources/HaCWebsiteLib/Controllers/ConstitutionController.swift
Sources/HaCWebsiteLib/Controllers/GitHubWebhookController.swift
Sources/HaCWebsiteLib/Utils/GitUtils.swift
Sources/HaCWebsiteLib/ViewModels/Constitution.swift
Sources/HaCWebsiteLib/routes.swift
static/src/styles/Constitution.styl
static/src/styles/main.styl

Fixes #103 .
Changes:
- a route `/constitution` is added that will show the latest version of constitution
- the constitution is loaded directly from the [constitution repository](https://github.com/hackersatcambridge/constitution)
- a webhook has been added to update the version of the constitution the site uses, and webhook controller is now configurable

Add a route for the constitution

---

Sources/HaCWebsiteLib/ViewModels/LandingPage/LandingFeatures/ProgrammingInRust.swift

Now points to repo at https://github.com/hackersatcambridge/intro-to-rust-workshop

Update rust live link

---

Sources/HaCWebsiteLib/ViewModels/LandingPage/LandingPage.swift
static/src/styles/landing/LandingIntroduction.styl

Make mission statement big

---

static/src/styles/core/interaction.styl

Add subtle button shadow

---

Package.resolved
Package.swift

This PR will bump Kitura up to v2.0.0.
The reason for this is that the old version of Kitura causes a dependency resolution conflict when trying to add the Credentials dependency.

Bump Kitura to v2.0.0

---

Sources/HaCWebsiteLib/ViewModels/Script.swift

Previously were assuming we were running in `/root/hac-website`. Now we don't depend on that

Make Script loading portable

---

Sources/HaCWebsiteLib/routes.swift

Done because the posters have this link, and we don't really want that to redirect to the Facebook events anymore.

Make /game-gig redirect to the web page

---

Sources/HaCWebsiteLib/Models/Link.swift

Previously I'd renamed a stored prop and didn't update method. This fixes that bug

Fix for bad equatable

---

Sources/HaCWebsiteLib/Middleware/ErrorRoutingMiddleware.swift
Sources/HaCWebsiteLib/Views/ServerError.swift
Sources/HaCWebsiteLib/routes.swift
static/src/styles/ServerError.styl
static/src/styles/main.styl

Fixes #58. 
This PR adds new middleware which will serve a new error page if an error is thrown in any of our routes.
This PR only introduces an error code 500 page which is the most general of server-side errors. This error page also follows the exact same format as the `NotFound` middleware for consistency.
Previously:
Now:

Add route error handling

---

Sources/HaCTML/Fragment.swift
Sources/HaCTML/HTMLElement.swift
Sources/HaCWebsiteLib/Views/BackBar.swift
Sources/HaCWebsiteLib/Views/Workshops/IndividualWorkshopPage.swift
Sources/HaCWebsiteLib/Views/Workshops/WorkshopsIndexPage/WorkshopsIndexPage.swift
static/src/styles/ContentCard.styl
static/src/styles/Workshop/WorkshopContent.styl
static/src/styles/Workshop/WorkshopDescription.styl
static/src/styles/Workshop/WorkshopFurtherReading.styl
static/src/styles/Workshop/WorkshopHero.styl
static/src/styles/Workshop/index.styl
static/src/styles/core/brand.styl
static/src/styles/core/color.styl
static/src/styles/core/interaction.styl
static/src/styles/core/text.styl
static/src/styles/main.styl

Fixes #159
Notable missing:
- Good handling of code snippets
- Embedding of any content (slides or recording), might not be particularly convenient to do this anyway
Now

Style the individual workshop page

---

Sources/HaCWebsite/main.swift
Sources/HaCWebsiteLib/Controllers/WorkshopsController.swift
Sources/HaCWebsiteLib/Views/Workshops/IndividualWorkshopPage.swift
Sources/HaCWebsiteLib/Views/Workshops/WorkshopsIndexPage/WorkshopsIndexArchive.swift
Sources/HaCWebsiteLib/Views/Workshops/WorkshopsIndexPage/WorkshopsIndexPage.swift
Sources/HaCWebsiteLib/routes.swift
static/src/styles/WorkshopsIndex/WorkshopsIndexArchive.styl
static/src/styles/WorkshopsIndex/index.styl

Fixes #197 
- Plugs in the IndividualWorkshopPage view to the given data
- Plugs in the WorkshopsIndexPage to available data by removing the events schedule and replaced with a workshops archive for now. The schedule should be reintroduced later.

Hook up NewWorkshops data to View

---

Package.resolved
Sources/HaCWebsiteLib/Models/Background.swift
Sources/HaCWebsiteLib/Models/NewWorkshop+init.swift
Sources/HaCWebsiteLib/NewWorkshopManager.swift
Sources/HaCWebsiteLib/Utils/GitUtil.swift
Tests/HaCWebsiteLibTests/NewWorkshopTests.swift

Fixes #198 
This adds support for fetching the SHA of the current master for workshop repos, and using that to generate a production URL for RawGit. Note that I haven't tested the fetching of the SHA, but I have added tests to make sure the data is used appropriately.
I also refactored the workshop init function a bit, to save ourselves from passing lots of data around.

Serve images with RawGit's production URLs

---

Package.resolved
Package.swift
Sources/HaCWebsiteLib/Markdown+relativeURLs.swift
Sources/HaCWebsiteLib/Markdown.swift
Sources/HaCWebsiteLib/Models/NewWorkshop+init.swift
Tests/HaCWebsiteLibTests/MarkdownTests.swift
Tests/HaCWebsiteLibTests/Resources/MarkdownRelativeURLTestData/absolute_only.md
Tests/HaCWebsiteLibTests/Resources/MarkdownRelativeURLTestData/brackets.md
Tests/HaCWebsiteLibTests/Resources/MarkdownRelativeURLTestData/some_relative.md
Tests/LinuxMain.swift

Fixes #192 
Adds support for images at relative URLs in notes by resolving relative URLs at the import stage.

Add relative URL resolution to Markdown

---

Sources/HaCWebsiteLib/DatabasePreparations.swift
Sources/HaCWebsiteLib/Events/GeneralEvent.swift
Sources/HaCWebsiteLib/Utils/DatabaseUtils.swift
Sources/HaCWebsiteLib/routes.swift

This uses Fluent built-in preparation manager to handle preparations (so they only run once). Previously we were managing this on our own.
I've verified that preparations successfully run, and do not re-run or error when they have already run.
We will need to nuke the DB in prod before this is shipped, but there is no useful data up there.
@CharlieCrisp could you validate that what I am doing is OK?

Use Fluent to automatically run migrations

---

Sources/HaCWebsiteLib/Assets.swift
Sources/HaCWebsiteLib/DatabasePreparations.swift
Sources/HaCWebsiteLib/routes.swift
package.json

This fixes the cryptic error we were getting from Heroku. It was due to the lack of type annotation on `DatabasePreparations.preparations`. It should have been a type error, but was instead crashing the compiler (only in release configuration).
To help us prevent these issues from happening in the future, I've added a production build to our test suite. It adds time to our travis build unfortunately, but it reduces the difference between our test environment and production.
I've also fixed up a deprecation warning we were getting, but that's unrelated (in Assets)

Fix issues with deployment and add production build to tests

---

Sources/HaCWebsiteLib/Views/Hackathons/GameGig2017/GameGig2017.swift
Sources/HaCWebsiteLib/Views/Page.swift
Sources/HaCWebsiteLib/Views/Workshops/IndividualWorkshopPage.swift

Fixes #221  .
Previously
Now
This change also allows for general postFix changes on pages as well.

Add workshop syntax highlighting

---

Sources/HaCWebsiteLib/Models/Workshop+init.swift
Tests/HaCWebsiteLibTests/Resources/WorkshopTestData/workshop-missing-tags/info/metadata.yaml

Makes `thanks` and `further_reading_links` fields of workshop metadata files optional, modelling them as empty lists in Swift when they are omitted from the Yaml file.

Optional fields

---

Sources/HaCWebsiteLib/Controllers/WorkshopsController.swift
Sources/HaCWebsiteLib/Markdown.swift
Sources/HaCWebsiteLib/Models/Workshop+init.swift
Sources/HaCWebsiteLib/Views/Workshops/IndividualWorkshopPage.swift
Sources/HaCWebsiteLib/routes.swift
docker-compose.yml
static/src/styles/core/flash.styl
static/src/styles/core/index.styl

Fixes #222 
Adds a route `/workshops/validate/:workshopId`
That parses the workshop repo at `github.com/hackersatcambridge/workshop-<workshopId>` and prints results for quick validation of workshop repos.
Some results: 
There is an issue with this in the dev environment. Trying to validate a workshop where the repo doesn't exist will cause an indefinite request and subsequent reloads of the server in the dev environment will fail due to this request still holding the port open (as far as I can tell). This is due to the Git command requesting a username which can't be given so hangs.

Add a workshop validation route

---

Sources/HaCWebsiteLib/Views/Workshops/IndividualWorkshopPage.swift
static/src/styles/core/interaction.styl

Adding license button to the workshop pages with the format "License: " + SPDX Identifier which will take you to the GitHub License file for that particular workshop. Styling is just the "$Color__bright2". Resolving issue #235 . 
Previously
Now

Add License Button to Workshops

---

Sources/HaCWebsiteLib/Controllers/WorkshopsController.swift
Sources/HaCWebsiteLib/Views/LandingPage/LandingFeatures/ContinuousIntegrationWorkshop.swift
Sources/HaCWebsiteLib/Views/LandingPage/LandingFeatures/EmacsWorkshop.swift
Sources/HaCWebsiteLib/Views/LandingPage/LandingFeatures/IntroToSwift.swift
Sources/HaCWebsiteLib/Views/LandingPage/LandingFeatures/OpenSourceWorkshop.swift
Sources/HaCWebsiteLib/Views/LandingPage/LandingFeatures/PythonML.swift
Sources/HaCWebsiteLib/WorkshopManager.swift

This change means that now the workshop manger indexes workshops by
their IDs instead of their repo names as well.
Fixes #243 and fixes #254 .

Assume workshops repo uses workshopIDs not URLs

---

Package.resolved
Sources/HaCWebsiteLib/Controllers/AboutController.swift
Sources/HaCWebsiteLib/Views/LandingPage/LandingPage.swift
Sources/HaCWebsiteLib/routes.swift

**DO NOT MERGE UNTIL EVERYONE HAS GIVEN PERMISSION TO HAVE THEIR NAMES ON THE SITE**
Adding about page primarily so we can hand over the ownership of Slack, hence it contains only the bare minimum information about the society (we can expand on this later in the year) but also our names.
Now the landing page looks like:
And the 'about us' button redirects to '/about'

Add initial about page
